version: '3.7'
services:
  db:
    image: 'postgres'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=autoatlas-affiliate'
    volumes:
      - './development/data:/var/data/db'
  test_db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=autoatlas-affiliate-test'
    volumes:
      - './development/test_data:/var/data/test_db'
